name: Venv test windows

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Install Python 2.x
        uses: actions/setup-python@v1
        with:
          python-version: '2.x'
      - name: Install virtualenv
        run: pip install virtualenv
      - name: Create virtualenv
        run: C:\ProgramData\Chocolatey\bin\python2.exe -B -E -s virtualenv.py --no-download C:\Users\runneradmin\.vpython-root\6ed5d3
