name: Venv test windows

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Install Python 2.x
        uses: actions/setup-python@v1
        with:
          python-version: '2.x'
      - name: Create virtualenv
        run: virtualenv venv
